### ISSUE TITLE
Why the page header is often ignored in model's output?

### ISSUE THREAD

**Issue by bryanyzhu** [facebookresearch/nougat#199]
First of all, great work, the model works really well! 

I just have a quick question. I noticed that for most pdf pages, the model's output doesn't contain headers (running titles, running authors, page numbers, etc.). This is great, because we don't need further post-processing. But there are still some cases that these headers show up. So my question is, does Nougat explicitly do anything to ignore these headers, or it is just these headers are mostly removed from training data? Thank you. 

For example, on the official webpage of Nougat, example 5 recognizes the header as section name (but miss the first line), while all other examples ignore these headers.

**Comment by lukas-blecher** [comment]
Thank you,

yes we removed the headers from the training data. And it works pretty well for pdfs however the scanned documents are out of distribution and might show unwanted artifacts.

That the fist line is missing is a bit weird. not 100% sure, but could be due to an unrelated issue with the page splitting algorithm.

**Comment by bryanyzhu** [comment]
Thanks, it indeed works really well. I'm curious to know the motivation of removing headers when preparing the training image-latex pair, is it beneficial for page splitting,  or for easier post-processing, or something else? Appreciate it.

**Comment by lukas-blecher** [comment]
yes, both actually:)
