### ISSUE TITLE
RuntimeError: CUDA error: out of memory'

### ISSUE THREAD

**Issue by gk966988** [facebookresearch/nougat#47]
Is the current code for distributed training? I trained on a machine with 4 GPUs each with 24GB of memory, but still encountered the error `RuntimeError: CUDA error: out of memory`
**How to solve this problem？**

**Comment by marwinsteiner** [comment]
> Is the current code for distributed training? I trained on a machine with 4 GPUs each with 24GB of memory, but still encountered the error `RuntimeError: CUDA error: out of memory` **How to solve this problem？**



I have 2 GPUs and would like Nougat to use both -- have you been able to get Nougat to access the shared memory when using pytorch under the hood for conversion? After installing pytorch, Nougat seems to default to only one GPU out of the two, instead of using both...

I tried increasing the batch size using the --batchsize command in the cli and ran into the same issue but actually because I ran out of memory.

**Comment by lukas-blecher** [comment]
> Is the current code for distributed training? I trained on a machine with 4 GPUs each with 24GB of memory, but still encountered the error `RuntimeError: CUDA error: out of memory` **How to solve this problem？**

I trained with 40GB A100s. Maybe are able to train the model if you use another strategy 
https://github.com/facebookresearch/nougat/blob/f7d42f86e6bec683b01ffb825ebcfd962c59f9d0/train.py#L183C14
https://lightning.ai/docs/pytorch/latest/advanced/model_parallel.html
